version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      # MONGO_INITDB_DATABASE: teste
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: teste
 
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: teste
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_SERVER: mongodb